name: banking
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  provider: ^6.1.2
  pinput: ^5.0.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.5
  loading_indicator: ^3.1.1
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.0.0
  dotted_line: ^3.2.0
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  badges: ^3.1.2
  # scan: ^1.6.0
  # images_picker: ^1.2.11
  fl_chart: ^0.65.0
  # qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.5.2
  face_camera: ^0.1.4
  local_auth: ^2.3.0
  # firebase_auth: ^4.15.0
  http: ^1.4.0
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  device_info_plus: ^11.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
  
